export const ADD_PRODUCT = 'ADD_PRODUCT';
export type ADD_PRODUCT = typeof ADD_PRODUCT;

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export type REMOVE_PRODUCT = 'REMOVE_PRODUCT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export type GET_PRODUCTS = 'GET_PRODUCTS';